version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "7000:5432"
    networks:
      - apinetwork
    volumes:
      - api_data:/var/lib/postgresql/data 
    healthcheck:
      test: pg_isready -U bayau -d dbjr -h localhost && echo "que es esto"
      interval: 3s
      timeout: 20s
      retries: 5
  golang-server:
    image: fmapi:2.0
    container_name: go-server
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - apinetwork
    ports:
      - "8080:8080"

networks:
  apinetwork:
volumes:
  api_data: